all: rowbycol/updated sigmabyt/updated ts/updated curtains/updated

rowbycol/updated: make_rowbycol.py
	python $<

sigmabyt/updated: make_sigmabyt.py
	python $<

ts/updated: make_sigmabyt_ts.py
	python $<

curtains/updated: make_curtains.py
	python $<

