
all: link

link:
	ln -fs /work/ROMO/global/CMAQv5.2.1/2016fe_spinup_cb6_15jh/108km/basecase/output/CONC/CCTM_CONC_v521_intel17.0_HEMIS_cb6_2015122[2-9] .
	ln -fs /work/ROMO/global/CMAQv5.2.1/2016fe_spinup_cb6_15jh/108km/basecase/output/CONC/CCTM_CONC_v521_intel17.0_HEMIS_cb6_2015123[0-9] .
	ln -fs /work/ROMO/global/CMAQv5.2.1/2016fe_hemi_cb6_16jh/108km/basecase/output/CONC/CCTM_CONC_v521_intel17.0_HEMIS_cb6_2016* .

clean:
	rm CCTM_CONC_v521_intel17.0_HEMIS_cb6_????????
